### PR TITLE
Fix and clean up exception definitions

### PR DESCRIPTION
**Pull request by nbr23**
Hello,
Exceptions seem to not be working properly, I took the liberty of simplifying a tad and fixing them.
Cheers,
Max

### CODE REVIEW

**Comment by kosalaat** [comment]
Hi Max, thanx for the patch. Just curious which exception didn't work. I
have test scripts testing most of the exceptions for both for 2.7 and 3.X.
maybe I can update the test scripts to cover the scenario you had issues
with.

Cheers,
*Kosala*

**Comment by nbr23** [comment]
Hi Kosala,
The exception test script seems to work for me, however raising an exception and handling them in actual scenario fails "incorrectly".
Let's consider the following script:
```
from Actifio import Actifio

act = Actifio(REAL_IP, REAL_USER, WRONG_PASSWORD)

act.get_hosts()
```

If I run it currently, it fails as such:
```
Invalid username or password
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    act.get_hosts()
  File "/actifio-python-package/Actifio/Actifio.py", line 429, in get_hosts
    lshost_out = self.run_uds_command('info', 'lshost', {})
  File "/actifio-python-package/Actifio/Actifio.py", line 49, in decorated
    Actifio._create_session(cls)
  File "/actifio-python-package/Actifio/Actifio.py", line 225, in _create_session
    raise ActLoginError("Invalid username or password")
Actifio.actexceptions.ActLoginError: <exception str() failed>
```
The str() over the exception is failing, so python cannot print it.

After applying the attached patch, the same gives:
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    act.get_hosts()
  File "/actifio-python-package/Actifio/Actifio.py", line 429, in get_hosts
    lshost_out = self.run_uds_command('info', 'lshost', {})
  File "/actifio-python-package/Actifio/Actifio.py", line 49, in decorated
    Actifio._create_session(cls)
  File "/actifio-python-package/Actifio/Actifio.py", line 225, in _create_session
    raise ActLoginError("Invalid username or password")
Actifio.actexceptions.ActLoginError: Actifio Login Exception: Invalid username or password
```

Cheers,
Max

**Comment by kosalaat** [comment]
Hi Max,

For Python 2.7 and 3.7 I couldn't reproduce the error you described, as you
can see it is covered in the test scenarios. Which version are you using?
and have you cloned the module from GitHub or have you installed it using
pip? If you've installed with pip, what does the "pip show Actifio" say for
the version?


*Kosala*

**Comment by nbr23** [comment]
Hi Kosala,

I was able to reproduce independently using a clean container, so you should be able to use the same to verify.
I run a simple test, just importing actexceptions and raising an expression directly to show pinpoint only the erroneous code (the message handling part of the exception).

```Dockerfile
FROM python:3.7

RUN apt update && apt install -y git python3-pip \
  && pip install urllib3 \
  && git clone https://github.com/Actifio/actifio-python-package.git
RUN apt search urllib3 python
WORKDIR actifio-python-package
CMD python3 -V && python3 -c "from Actifio.actexceptions import ActLoginError; raise ActLoginError('This message should be displayed when the error is raised')"
```
Then building and running it:
`docker build . -t actest && docker run actest`

The result is:

> Python 3.7.8
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> Actifio.actexceptions.ActLoginError: <**exception str() failed**>

Trying with the submitted patch:
```Dockerfile
FROM python:3.7

RUN apt update && apt install -y git python3-pip \
  && pip install urllib3 \
  && git clone -b exceptions --single-branch https://github.com/nbr23/actifio-python-package.git
RUN apt search urllib3 python
WORKDIR actifio-python-package
CMD python3 -V && python3 -c "from Actifio.actexceptions import ActLoginError; raise ActLoginError('This message should be displayed when the error is raised')"
```

Result:
> Python 3.7.8
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> Actifio.actexceptions.ActLoginError: **Actifio Login Exception: This message should be displayed when the error is raised**

I tried the same with 2.7 containers:
master:

> Python 2.7.18
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> Actifio.actexceptions.ActLoginError: **<exception str() failed>**

patch submitted:
> Python 2.7.18
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> Actifio.actexceptions.ActLoginError: **Actifio Login Exception: This message should be displayed when the error is raised**

I hope this makes it more clear, let me know if you have any questions.

Cheers,
Max

**Comment by nbr23** [comment]
Closing this as it seems fixed with https://github.com/Actifio/actifio-python-package/commit/643ab7a26d98c804ff1ded84e9a67cccd965175e
Thanks!

**Pull request closed without merging**
